### PR TITLE
Leslie part1

### PR DESCRIPTION
**Pull request by Leslie-C**
Some progress 😄. All the chapters in part 1 should exist now, not done with edits/updates, but all existing p1 material has been "migrated".

### CODE REVIEW

**Comment by oneilsh** [comment]
Leslie! It's good to hear from you, how have you been?

**Comment by Leslie-C** [comment]
Busy busy, as always it seems! Preparing for our next cohort to begin in June. How about you? We need to catch up sometime!

**Comment by oneilsh** [comment]
Much the same lol. Doing more research recently which has been a nice change. Though I did just finish up a new course on electronic health record data analysis which was fun. Yeah I need to get down to Eugene!

**Comment by Leslie-C** [comment]
Oooooo - we should totally connect! We're exploring a new track in biomedical data science. We've hired one of our alumni to work on developing this, and she'll be in town for our summer courses.

**Pull request merged**
